apps/cart/urls.py
from django.conf.urls import url
from .views import AddCartView, CartInfoView, UpdateCartView, DeleteCartView
from utils.login import  login_required
app_name = 'cart'
urlpatterns = [
    url(r'^add$', AddCartView.as_view(), name='add'),
    # 只有登录的用户才有购物车
    url(r'^$', login_required(CartInfoView.as_view()), name='cart'),
    url(r'^update$', login_required(UpdateCartView.as_view()), name='update'),
    url(r'^delete$', login_required(DeleteCartView.as_view()), name='delete')
]

apps/goods/urls.py
from django.conf.urls import url
from .views import IndexView, DetailView, ListView
from . import views
app_name = 'goods'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name="detail"),
    url(r'^list/(?P<type_id>\d+)/(?P<page_num>\d+)$', ListView.as_view(), name='list')
]

apps/orders/urls.py
from django.conf.urls import url
from .views import PlaceOrderView, HandleOrderView
from utils.login import login_required
app_name = 'orders'
urlpatterns = [
    url(r'^place_orders$', login_required(PlaceOrderView.as_view()), name='place_orders'),
    url(r'^commit$', login_required(HandleOrderView.as_view()), name='commit'),
]

apps/users/urls.py
from django.conf.urls import url
from .views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, UserSiteView, LogOutView
# 使用自定义login_required
from utils.login import login_required
app_name = 'users'
urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^user_center_info$', login_required(UserInfoView.as_view()), name='user_center_info'),
    url(r'^user_center_order/(?P<page_num>\d+)$', login_required(UserOrderView.as_view()), name='user_center_order'),
    url(r'^user_center_site$', login_required(UserSiteView.as_view()), name='user_center_site'),
    url(r'^logout$', LogOutView.as_view(), name='logout')
]

# 1. login_required 不能用于视图类，需要手动调用
# 2. login_required 默认跳转到account/login?next=， settings.py:LOGIN_URL指定跳转页面

daily_fresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('', include('goods.urls', namespace='goods')),
    path('search/', include('haystack.urls')) # 全文检索框架
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from db.base_model import BaseModel

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin, BaseModel):
    '''用户信息表'''

    username = models.CharField(max_length=20, verbose_name='用户名', unique=True)
    first_name = models.CharField(max_length=10, verbose_name='名')
    last_name = models.CharField(max_length=10, verbose_name='姓')
    email = models.EmailField(max_length=255, verbose_name='邮箱')

    is_active = models.BooleanField(default=True, verbose_name='是否激活')
    is_superuser = models.BooleanField(default=False, verbose_name='是否是管理员')
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def generate_active_token(self):
        '''生成用户签名'''
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {'confirm': self.id}
        token = serializer.dumps(info)
        return token.decode()

    class Meta:
        db_table = 'User'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

class AddressManager(models.Manager):

    def get_default_address(self, user):
        try:
            address = self.get(user=user, is_default=True)
        except self.model.DoesNotExist:
            address = None
        return address

class Address(BaseModel):
    '''地址表'''

    receiver = models.CharField(max_length=20, verbose_name='收件人')
    address = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮编')
    contact = models.CharField(max_length=11, verbose_name='联系方式')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')
    # 定义外键
    user = models.ForeignKey('User', verbose_name='所属用户', on_delete=models.CASCADE)
    objects = AddressManager()

    class Meta:
        db_table = 'Address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
# Create your views here.




class CartInfoView(View):

    def get(self, request):
        user = request.session.get('user')
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_amount = 0
        total_price = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            sku_price = sku.price * int(count)

            sku.sku_price = sku_price
            sku.sku_count = count.decode()
            total_amount += int(count)
            total_price += sku_price
            skus.append(sku)

        context = {
            'skus': skus,
            'total_amount': total_amount,
            'total_price': total_price
        }

        return render(request, 'cart.html', context)

# /cart/add 接受商品id和数量
class AddCartView(View):
    '''添加购物车'''

    def post(self, request):

        user = request.session.get('user', None)

        if not user:
            return JsonResponse({'status': -1, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        amount = request.POST.get('amount')

        # 数据校验
        if not all([sku_id, amount]):
            return JsonResponse({'status': 0, 'errmsg': '数据不完整'})

        try:
            amount = int(amount)
        except ValueError:
            return JsonResponse({'status': 0, 'errmsg': '商品信息不合法'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'status': 0, 'errmsg': '商品不存在'})

        # 写入数据库
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        # 检查商品是否已存在
        cart_res = conn.hget(cart_key, sku_id)
        if cart_res:
            amount += int(cart_res)

        if amount > sku.stock:
            return JsonResponse({'status': 0, 'errmsg': '库存不足'})
        # hset：已存在更新，不存在添加
        conn.hset(cart_key, sku_id, amount)

        totoal_count = conn.hlen(cart_key)
        return JsonResponse({'status': 1, 'total_count': totoal_count, 'errmsg': '添加成功'})

class UpdateCartView(View):
    def post(self, request):

        user = request.session.get('user', None)

        if not user:
            return JsonResponse({'status': -1, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        amount = request.POST.get('amount')
        # 数据校验
        if not all([sku_id, amount]):
            return JsonResponse({'status': 0, 'errmsg': '数据不完整'})

        try:
            amount = int(amount)
        except ValueError:
            return JsonResponse({'status': 0, 'errmsg': '商品信息不合法'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'status': 0, 'errmsg': '商品不存在'})

        if amount > sku.stock:
            return JsonResponse({'status': 0, 'errmsg': '库存不足'})

        # 写入数据库
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        conn.hset(cart_key, sku_id, amount)

        val_list = conn.hvals(cart_key)
        sumds = sum([int(v) for v in val_list])
        return JsonResponse({'status': 1, 'sum': sumds, 'msg': '更新成功'})

class DeleteCartView(View):
    def post(self, request):

        user = request.session.get('user', None)
        if not user:
            return JsonResponse({'status': -1, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')

        if not sku_id:
            return JsonResponse({'status': 0, 'errmsg': '商品信息不完整'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'status': 0, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id

        conn.hdel(cart_key, sku_id)

        val_list = conn.hvals(cart_key)
        sumds = sum([int(v) for v in val_list])
        return JsonResponse({'status': 1, 'sum': sumds, 'msg':'删除成功'})

templates/base.html
{# 首页 注册 登录 #}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %} {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/main.css' %}">

	{% block jsfiles %}{% endblock jsfiles %}

</head>
<body>
	{% block header %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.user %}
				<div class="login_btn fl">
					欢迎您：<em><b>{{ request.session.user.username }}</b></em>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出登录</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'users:user_center_order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
	{% endblock header %}

	{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form method="get" action="{% url 'haystack_search' %}" role="search">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
	{% endblock search %}

	{% block body %}
	{% endblock body %}

	{% block footer %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	{% endblock footer %}

	{% block bottom %}
	{% endblock bottom %}

	{% block footer_files %}
	{% endblock footer_files %}
</body>
</html>

templates/detail.html
{% extends 'detail_list_base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}

{% block main_content %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.type.id 1 %}">{{ sku.type.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_price">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					{% csrf_token %}
					<input type="text" class="num_show fl" value="1" onblur="vali_amount(this)">
					<a href="javascript:void()" class="add fr" onclick="change_amount(this)">+</a>
					<a href="javascript:void()" class="minus fr" onclick="change_amount(this)">-</a>
				</div> 
			</div>
			<div>
				<p>其他规格：</p>
				<ul>
					{% for sku in peer_skus %}
					<li>
						<a href = "{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
					</li>
					{% endfor %}
				</ul>
			</div>
			<div class="total">总价：<em></em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" sku_id = {{ sku.id }} class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }} </dd>
				</dl>
			</div>

				<div class="tab_content">
				<dl>
					{% for order in sku_orders %}
					<dt>评论时间：{{ order.update_time }} &nbsp; {{ order.order.user.username }}</dt>
					<dd>{{ order.comment }} </dd>
					{% endfor %}
				</dl>
			</div>

		</div>
	</div>
{% endblock main_content %}

{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}

{% block footer_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/goods_detail.js' %}"></script>
{% endblock footer_files %}

templates/detail_list_base.html
{# detail list #}
{% extends 'base.html' %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}
    {% endblock main_content %}
{% endblock body %}≥

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block jsfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock jsfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %}
			<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% empty %}
			暂无种类
			{% endfor %}

		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for banner in goods_banner %}
				<li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for promotion in promotion_banner %}
			<a href="#"><img src="{{ promotion.image.url }}"></a>
			{% endfor %}
		</div>
	</div>

	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for title in type.title_banner %}
				<a href="{% url 'goods:detail' title.sku.id %}">{{ title.sku.name }}</a>
				{% endfor %}

			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
				{% for image in type.image_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' image.sku.id %}">{{ image.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' image.sku.id %}"><img src="{{ image.sku.image.url }}"></a>
					<div class="prize">¥ {{ image.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}
{% endblock body %}

{% block footer_files %}
	<script type="text/javascript" src="{% static 'js/slideshow.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock footer_files %}

templates/list.html
{% extends 'detail_list_base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>> </span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}?sort=default" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="javascript:void(0)" class="add_goods" id="add_cart" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if page.has_previous %}
				<a href="{% url 'goods:list' type.id page.previous_page_number %}?sort={{ sort }}">上一页</a>
				{% else %}
				<a href = "#" >上一页</a>
				{% endif %}
				{% for page_index in page.paginator.page_range %}
				{% if page_index == page.number %}
				<a href="{% url 'goods:list' type.id page_index %}?sort={{ sort }}" class="active">{{ page_index }}</a>
				{% else %}
				<a href="{% url 'goods:list' type.id page_index %}?sort={{ sort }}" >{{ page_index }}</a>
				{% endif %}
				{% endfor %}
				{% if page.has_next %}
				<a href="{% url 'goods:list' type.id page.next_page_number %}?sort={{ sort }}">下一页></a>
				{% else %}
				<a href = "#" >下一页</a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% load filters %}

{% block title %}天天生鲜-提交订单{% endblock title %}
{% block page_title %}&nbsp;&nbsp;&nbsp;提交订单{% endblock page_title %}

	{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			{% for address in address_list %}
			<dd>
				<input type="radio" name="address_id" value="{{ address.id }}" {% if address.is_default %}checked{% endif %}>
				{{ address.address }} （{{ address.receiver }} 收）
				{{ address.contact|phone_filter }}
			</dd>
			{% empty %}
			没有添加收货地址
			{% endfor %}

		</dl>
		<a href="{% url 'users:user_center_site' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked value="0">
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="1">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="2">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="3">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
		{% csrf_token %}
		{% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{sku.amount }}</li>
			<li class="col07">{{ sku.good_sum }}元</li>
		</ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ express_fee }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_bill }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:void(0);" id="order_btn" sku_ids = {{ sku_ids }}>提交订单</a>
	</div>	
	{% endblock body %}


	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	{% block footer_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/place_order.js' %}"></script>
	{% endblock footer_files %}

templates/user_center_base.html
{# 用户相关 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心 {% endblock page_title %}

{% block body %}
<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:user_center_info' %}" {% if page == 'user' %}class = 'active'{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'users:user_center_order' 1 %}" {% if page_name == 'order' %}class = 'active'{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'users:user_center_site' %}" {% if page == 'site' %}class = 'active'{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
    {% block right_content %}
    {% endblock right_content %}
</div>
{% endblock body %}

templates/user_center_info.html
{% extends 'user_center_base.html' %}
{% load staticfiles %}

		{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ current_user.username }}</li>
							{% if address %}
							<li><span>联系方式：</span>{{ address.contact }}</li>
							<li><span>联系地址：</span>{{ address.address }}</li>
							{% else %}
							<li><span>联系方式：</span>无默认联系方式</li>
							<li><span>联系地址：</span>无默认联系地址</li>
							{% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

						{% for good in good_history %}
						<a href="detail.html"><img src="{{ good.image.url }}"></a> {# fastdfs 存储图片 #}
						<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
						<div class="operate">
							<span class="prize">￥{{ good.price }}</span>
							<span class="unit">{{ good.unite }} / {{ good.price }}</span>
							<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
						{% empty %}
						暂无历史浏览记录
						{% endfor %}
			</ul>
		</div>
		</div>
		{% endblock right_content %}